### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getText' of undefined

### ISSUE THREAD

**Issue by nadesho3er** [LukasMeine/devmind-beautifier#6]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [devmind-beautifier](https://github.com/LukasMeine/devmind-beautifier) package 1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getText' of undefined

```
At C:\Users\jpd\.atom\packages\devmind-beautifier\lib\devmind-beautifier.js:85

TypeError: Cannot read property 'getText' of undefined
    at Object.toggle (/packages/devmind-beautifier/lib/devmind-beautifier.js:85:19)
    at HTMLElement.devmindBeautifierToggle (/packages/devmind-beautifier/lib/devmind-beautifier.js:64:49)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:349576)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:11:348051)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:765573)
    at EventEmitter.t (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:1:773496)
    at EventEmitter.emit (events.js:194:13)
```

### Commands

```
     -9:21.7.0 emmet:update-tag (input.hidden-input)
  4x -9:15 core:undo (input.hidden-input)
     -8:57 emmet:update-tag (input.hidden-input)
 13x -8:43.2.0 core:backspace (input.hidden-input)
     -4:55.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:55.2.0 editor:newline (input.hidden-input)
  5x -4:52.9.0 core:backspace (input.hidden-input)
     -4:47.5.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -4:47.5.0 editor:newline (input.hidden-input)
     -3:54.3.0 core:backspace (input.hidden-input)
  2x -3:44.9.0 core:confirm (input.hidden-input)
     -2:33.4.0 core:backspace (input.hidden-input)
     -0:22.2.0 devmind-beautifier:toggle (button.btn.icon.enablement.icon-playback-pause)
```

### Non-Core Packages

```
atom-beautify undefined 
atom-formatter-jsbeautify 1.1.2 
atom-ternjs 0.20.0 
autoclose-html-plus 0.27.2 
csslint 1.2.0 
devmind-beautifier 1.3.0 
emmet 2.4.3 
```

**Comment by LukasMeine** [comment]
Yes. It's is happening because I have shut down https://devmind.io I'm thinking about some alternatives, maybe creating a cloud function to keep this project alive as long as it keeps on the free tier.
